name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "Setting environment variables"
        echo "::set-env name=AWS_ACCESS_KEY_ID::$AWS_ACCESS_KEY_ID"
        echo "::set-env name=AWS_SECRET_ACCESS_KEY::$AWS_SECRET_ACCESS_KEY"
        echo "::set-env name=AWS_REGION::$AWS_REGION"
